export const FETCHING_MAILS_START = 'FETCHING_MAILS_START';
export const FETCHING_MAILS_SUCCESS = 'FETCHING_MAILS_SUCCESS';
export const FETCHING_MAILS_FAIL = 'FETCHING_MAILS_FAIL';

export const SELECT_MAIL = 'SELECT_MAIL';